repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry:  bash -c 'trufflehog filesystem --config=$PWD/generic.yml --json --no-verification $PWD > output.json'
        language: system
        stages: ["commit", "push"]
