repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --config=./generic.yml --json'
        language: system
        stages: ["commit", "push"]
