#!/bin/bash

REVIEWDOG_GIT_TOKEN=$1
REVIEWDOG_DIR=$2
REVIEWDOG_LVL=$3
REVIEWDOG_REPORTER=$4
REVIEWDOG_FILTER=$5
REVIEWDOG_FAIL=$6
REVIEWDOG_TFSEC_VERSION=$7

TRIVY_SCANTYPE=$8
TRIVY_IGNORE=$9
TRIVY_SEVERITY=$10

echo "Run Tfsec"
./tsec_check.sh REVIEWDOG_GIT_TOKEN REVIEWDOG_DIR REVIEWDOG_LVL REVIEWDOG_REPORTER REVIEWDOG_FILTER REVIEWDOG_FAIL REVIEWDOG_TFSEC_VERSION

echo "Run Trivy"
./trivy_check.sh TRIVY_SCANTYPE TRIVY_IGNORE TRIVY_SEVERITY