#!/bin/bash

REVIEWDOG_GIT_TOKEN=$1
REVIEWDOG_DIR=$2
REVIEWDOG_LVL=$3
REVIEWDOG_REPORTER=$4
REVIEWDOG_FAIL=$5

TRIVY_SCANTYPE=$6
TRIVY_SCANREF=$7
TRIVY_IGNORE=$8
TRIVY_SEVERITY=$9

echo "Run Tfsec"
./tsec_check.sh REVIEWDOG_GIT_TOKEN REVIEWDOG_DIR REVIEWDOG_LVL REVIEWDOG_REPORTER REVIEWDOG_FAIL

echo "Run Trivy"
./trivy_check.sh TRIVY_SCANTYPE TRIVY_SCANREF TRIVY_IGNORE TRIVY_SEVERITY